#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-extra-enforcer-rules
Version  : 1.0.beta.9
Release  : 1
URL      : https://repo1.maven.org/maven2/org/codehaus/mojo/extra-enforcer-rules/1.0-beta-9/extra-enforcer-rules-1.0-beta-9.jar
Source0  : https://repo1.maven.org/maven2/org/codehaus/mojo/extra-enforcer-rules/1.0-beta-9/extra-enforcer-rules-1.0-beta-9.jar
Source1  : https://repo1.maven.org/maven2/org/codehaus/mojo/extra-enforcer-rules/1.0-beta-9/extra-enforcer-rules-1.0-beta-9.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-extra-enforcer-rules-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-extra-enforcer-rules package.
Group: Data

%description data
data components for the mvn-extra-enforcer-rules package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/extra-enforcer-rules/1.0-beta-9
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/extra-enforcer-rules/1.0-beta-9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/extra-enforcer-rules/1.0-beta-9
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/extra-enforcer-rules/1.0-beta-9


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/codehaus/mojo/extra-enforcer-rules/1.0-beta-9/extra-enforcer-rules-1.0-beta-9.jar
/usr/share/java/.m2/repository/org/codehaus/mojo/extra-enforcer-rules/1.0-beta-9/extra-enforcer-rules-1.0-beta-9.pom
